"""Assemble a Nix-built Python tool's runtime tree for native Windows execution.

home.stagedUvTools hands this the ``site-packages`` directory of the tool and of
every Python module in its runtime closure, as Nix built them on Linux. The
tree it writes is exactly what the package's own checks ran against: the files
are merged into one directory that the generated ``launch.py`` puts on
``sys.path``, so Windows needs nothing but a CPython of the right version (uv
provides it) and no dependency is resolved anywhere else.

The build fails on anything that cannot run there: a native extension, two
inputs shipping different bytes at one path, or a ``mainProgram`` with no
console-script entry point.
"""

from __future__ import annotations

import argparse
import configparser
import filecmp
import shutil
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

NATIVE_SUFFIXES = frozenset({".so", ".pyd", ".dylib", ".dll"})


class StageError(Exception):
    """A reason the tree cannot run natively on Windows."""


@dataclass(frozen=True)
class EntryPoint:
    module: str
    attr: str


class _EntryPoints(configparser.ConfigParser):
    """entry_points.txt keys are script names, which are case-sensitive."""

    def optionxform(self, optionstr: str) -> str:
        return optionstr


def _is_native(path: Path) -> bool:
    # `foo.cpython-312-x86_64-linux-gnu.so` and versioned `libfoo.so.1` alike.
    return path.suffix in NATIVE_SUFFIXES or ".so." in path.name


def merge(sources: Sequence[Path], out: Path) -> None:
    """Copy every file under each source into ``out``, skipping ``__pycache__``.

    Two sources may ship the same path only with identical bytes.
    """
    for source in sources:
        if not source.is_dir():
            raise StageError(f"{source}: not a site-packages directory")
        for path in sorted(source.rglob("*")):
            rel = path.relative_to(source)
            if "__pycache__" in rel.parts or path.is_dir():
                continue
            dest = out / rel
            if dest.exists():
                if not filecmp.cmp(path, dest, shallow=False):
                    raise StageError(f"{rel}: shipped with different contents by more than one input")
                continue
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, dest)


def native_files(tree: Path) -> list[Path]:
    return sorted(p.relative_to(tree) for p in tree.rglob("*") if p.is_file() and _is_native(p))


def find_entry_point(tree: Path, program: str) -> EntryPoint:
    """The ``[console_scripts]`` target named ``program`` across every dist-info."""
    found: list[str] = []
    for ep_file in sorted(tree.glob("*.dist-info/entry_points.txt")):
        parser = _EntryPoints(delimiters=("=",), interpolation=None)
        parser.read(ep_file, encoding="utf-8")
        if parser.has_option("console_scripts", program):
            found.append(parser.get("console_scripts", program).strip())
    if len(found) != 1:
        raise StageError(
            f"console script {program!r}: expected exactly one entry point, found {found or 'none'}"
        )
    target = found[0].split("[", 1)[0].strip()
    module, sep, attr = target.partition(":")
    if not sep or not module or not attr:
        raise StageError(f"console script {program!r}: malformed entry point {found[0]!r}")
    return EntryPoint(module=module.strip(), attr=attr.strip())


def render_launcher(entry: EntryPoint, program: str, requires_python: str) -> str:
    return f'''#!/usr/bin/env -S uv run --script
# /// script
# requires-python = "{requires_python}"
# dependencies = []
# ///
"""Runs {program} from the Nix-built tree beside this file.

Generated by nix-win home.stagedUvTools. Every module {program} imports was
staged here from its Nix build, so uv only provides the interpreter.
"""

import io
import sys
from importlib import import_module
from pathlib import Path

if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    # Windows defaults the std streams to the locale code page; tool I/O is UTF-8.
    if isinstance(sys.stdin, io.TextIOWrapper):
        sys.stdin.reconfigure(encoding="utf-8")
    for _stream in (sys.stdout, sys.stderr):
        if isinstance(_stream, io.TextIOWrapper):
            _stream.reconfigure(encoding="utf-8", line_buffering=True)
    _target = import_module({entry.module!r})
    for _part in {entry.attr!r}.split("."):
        _target = getattr(_target, _part)
    sys.exit(_target())
'''


def stage(sources: Sequence[Path], out: Path, program: str, requires_python: str) -> None:
    out.mkdir(parents=True, exist_ok=True)
    merge(sources, out)
    native = native_files(out)
    if native:
        listed = "\n  ".join(str(p) for p in native)
        raise StageError(f"native extensions cannot run on Windows CPython:\n  {listed}")
    entry = find_entry_point(out, program)
    (out / "launch.py").write_text(render_launcher(entry, program, requires_python), encoding="utf-8")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="staged-uv-tree", description=__doc__)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--main-program", required=True)
    parser.add_argument("--requires-python", required=True)
    parser.add_argument("sources", type=Path, nargs="+", help="site-packages directories")
    args = parser.parse_args(argv)
    try:
        stage(args.sources, args.out, args.main_program, args.requires_python)
    except StageError as exc:
        print(f"staged-uv-tree: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
