# Activation script framework for nix-win.
# Modules register named activation scripts with dependencies.
# The final activation script is assembled in topological order.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.system.activationScripts;

  activationLib = import ../lib/activation.nix { inherit lib; };

  # Build the concatenated activation script from all registered entries
  activationScript = activationLib.mkActivationScript cfg;
in
{
  options.system.activationScripts = lib.mkOption {
    # A bare string is accepted and coerced to { text; deps = [ ]; } — the
    # NixOS system.activationScripts shape.
    type = lib.types.attrsOf (
      lib.types.coercedTo lib.types.str (text: { inherit text; }) (
        lib.types.submodule {
          options = {
            text = lib.mkOption {
              type = lib.types.lines;
              default = "";
              description = "PowerShell script content for this activation phase.";
            };

            deps = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
              description = "Names of activation scripts that must run before this one.";
            };
          };
        }
      )
    );
    default = { };
    description = "Named activation script entries. Ordered by dependency DAG.";
  };

  config = {
    # Always register pre/post activation hooks (even if empty)
    # Default activation phases — always present, modules add text via mkBefore/mkAfter.
    # Chain: preActivation → files → scoop → winget → psmodules → dsc → serviceReloads → postActivation
    system.activationScripts.preActivation = { text = lib.mkDefault ""; deps = [ ]; };
    system.activationScripts.files = { text = lib.mkDefault ""; deps = [ "preActivation" ]; };
    system.activationScripts.scoop = { text = lib.mkDefault ""; deps = [ "files" ]; };
    system.activationScripts.winget = { text = lib.mkDefault ""; deps = [ "scoop" ]; };
    system.activationScripts.psmodules = { text = lib.mkDefault ""; deps = [ "winget" ]; };
    system.activationScripts.dsc = { text = lib.mkDefault ""; deps = [ "psmodules" ]; };
    system.activationScripts.serviceReloads = { text = lib.mkDefault ""; deps = [ "dsc" ]; };
    system.activationScripts.postActivation = { text = lib.mkDefault ""; deps = [ "serviceReloads" ]; };

    # Export the assembled activation script as a build artifact
    system.build.activationScript = pkgs.writeText "activate.ps1" ''
      # nix-win activation script
      # Generated by nix-win — do not edit manually.
      $ErrorActionPreference = 'Stop'
      Set-StrictMode -Version Latest

      ${activationScript}

      Write-Host "nix-win: activation complete." -ForegroundColor Green
    '';
  };
}
