# Activation script framework for nix-win.
# Modules register named activation scripts with dependencies.
# The final activation script is assembled in topological order.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.system.activationScripts;

  activationLib = import ../lib/activation.nix { inherit lib; };

  # Build the concatenated activation script from all registered entries,
  # each bracketed with a timing record.
  activationScript = activationLib.mkActivationScript cfg "system";
in
{
  options.system.activationScripts = lib.mkOption {
    # A bare string is accepted and coerced to { text; deps = [ ]; } — the
    # NixOS system.activationScripts shape.
    type = lib.types.attrsOf (
      lib.types.coercedTo lib.types.str (text: { inherit text; }) (
        lib.types.submodule {
          options = {
            text = lib.mkOption {
              type = lib.types.lines;
              default = "";
              description = "PowerShell script content for this activation phase.";
            };

            deps = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
              description = "Names of activation scripts that must run before this one.";
            };
          };
        }
      )
    );
    default = { };
    description = "Named activation script entries. Ordered by dependency DAG.";
  };

  config = {
    # Always register pre/post activation hooks (even if empty)
    # Default activation phases — always present, modules add text via mkBefore/mkAfter.
    # Chain: preActivation → files → scoop → winget → psmodules → dsc → serviceReloads → postActivation
    system.activationScripts.preActivation = { text = lib.mkDefault ""; deps = [ ]; };
    system.activationScripts.files = { text = lib.mkDefault ""; deps = [ "preActivation" ]; };
    system.activationScripts.scoop = { text = lib.mkDefault ""; deps = [ "files" ]; };
    system.activationScripts.winget = { text = lib.mkDefault ""; deps = [ "scoop" ]; };
    system.activationScripts.psmodules = { text = lib.mkDefault ""; deps = [ "winget" ]; };
    system.activationScripts.dsc = { text = lib.mkDefault ""; deps = [ "psmodules" ]; };
    system.activationScripts.serviceReloads = { text = lib.mkDefault ""; deps = [ "dsc" ]; };
    system.activationScripts.postActivation = { text = lib.mkDefault ""; deps = [ "serviceReloads" ]; };

    # Export the assembled activation script as a build artifact
    system.build.activationScript = pkgs.writeText "activate.ps1" ''
      # nix-win activation script
      # Generated by nix-win — do not edit manually.
      $ErrorActionPreference = 'Stop'
      Set-StrictMode -Version Latest

      ${activationLib.timingPrelude}

      # ── Per-item convergence ──────────────────────────────────────────
      # Steps that converge many items of one kind (scheduled tasks,
      # services, firewall rules, scripts) share one process, and this is
      # what keeps that from becoming a batch.
      #
      # Two properties matter, both of which DSC gave us and a naive port
      # would lose:
      #
      #   * Per ITEM reporting. One process is an implementation detail; the
      #     log must still say what happened to each item individually. A
      #     step that collapses N items into one line is a regression even
      #     when it is faster.
      #   * Per ITEM failure isolation. This script runs under
      #     $ErrorActionPreference = 'Stop' and Set-StrictMode, so an
      #     unguarded throw in item 3 of 11 abandons items 4-11 — which DSC
      #     does not do. Failures are collected and re-thrown once, at
      #     postActivation, so every item still gets its turn and the switch
      #     still fails.
      $script:NixWinFailures = [System.Collections.Generic.List[string]]::new()

      function Invoke-NixWinItem {
          param(
              [Parameter(Mandatory)][string]$Name,
              # Returns $true when the item is already in the desired state.
              [Parameter(Mandatory)][scriptblock]$Test,
              [Parameter(Mandatory)][scriptblock]$Set
          )
          try {
              # A test body that writes anything to the success stream returns
              # an ARRAY, and a non-empty array is always truthy — so a stray
              # `Write-Output` or an unassigned expression would silently make
              # every item report converged. Take the last emitted value, which
              # is the answer by the same convention DSC's TestScript uses.
              $verdict = & $Test
              if ($verdict -is [System.Array]) {
                  $verdict = if ($verdict.Length -gt 0) { $verdict[-1] } else { $false }
              }
              if ($verdict) {
                  Write-Host "  $Name ok" -ForegroundColor DarkGray
                  return
              }
              $sw = [System.Diagnostics.Stopwatch]::StartNew()
              & $Set
              $sw.Stop()
              Write-Host "  $Name changed ($([int]$sw.Elapsed.TotalMilliseconds) ms)" -ForegroundColor Green
          } catch {
              $script:NixWinFailures.Add("$Name`: $($_.Exception.Message)")
              Write-Host "  $Name FAILED: $($_.Exception.Message)" -ForegroundColor Red
          }
      }

      ${activationScript}

      if ($script:NixWinFailures.Count -gt 0) {
          throw "nix-win: $($script:NixWinFailures.Count) item(s) failed to converge:`n  " +
              ($script:NixWinFailures -join "`n  ")
      }

      Write-Host "nix-win: activation complete." -ForegroundColor Green
    '';
  };
}
