# Activation script framework for nix-win.
# Modules register named activation scripts with dependencies.
# The final activation script is assembled in topological order.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.win.activationScripts;

  activationLib = import ../lib/activation.nix { inherit lib; };

  # Build the concatenated activation script from all registered entries
  activationScript = activationLib.mkActivationScript cfg;
in
{
  options.win.activationScripts = lib.mkOption {
    type = lib.types.attrsOf (
      lib.types.submodule {
        options = {
          text = lib.mkOption {
            type = lib.types.lines;
            default = "";
            description = "PowerShell script content for this activation phase.";
          };

          deps = lib.mkOption {
            type = lib.types.listOf lib.types.str;
            default = [ ];
            description = "Names of activation scripts that must run before this one.";
          };
        };
      }
    );
    default = { };
    description = "Named activation script entries. Ordered by dependency DAG.";
  };

  config = {
    # Always register pre/post activation hooks (even if empty)
    # Default activation phases — always present, modules add text via mkBefore/mkAfter.
    # Chain: preActivation → files → scoop → winget → psmodules → dsc → serviceReloads → postActivation
    win.activationScripts.preActivation = { text = lib.mkDefault ""; deps = [ ]; };
    win.activationScripts.files = { text = lib.mkDefault ""; deps = [ "preActivation" ]; };
    win.activationScripts.scoop = { text = lib.mkDefault ""; deps = [ "files" ]; };
    win.activationScripts.winget = { text = lib.mkDefault ""; deps = [ "scoop" ]; };
    win.activationScripts.psmodules = { text = lib.mkDefault ""; deps = [ "winget" ]; };
    win.activationScripts.dsc = { text = lib.mkDefault ""; deps = [ "psmodules" ]; };
    win.activationScripts.serviceReloads = { text = lib.mkDefault ""; deps = [ "dsc" ]; };
    win.activationScripts.postActivation = { text = lib.mkDefault ""; deps = [ "serviceReloads" ]; };

    # Export the assembled activation script as a build artifact
    system.build.activationScript = pkgs.writeText "activate.ps1" ''
      # nix-win activation script
      # Generated by nix-win — do not edit manually.
      $ErrorActionPreference = 'Stop'
      Set-StrictMode -Version Latest

      ${activationScript}

      Write-Host "nix-win: activation complete." -ForegroundColor Green
    '';
  };
}
