# Scoop package manager module for nix-win.
# Mirrors nix-darwin's Homebrew module: declare packages → generate scoopfile.json → import on activation.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.scoop;

  # Generate scoopfile.json matching Scoop's export format.
  #
  # NOTE: `scoop import` does NOT honor the Version field for these entries,
  # and cannot be made to. scoop-import.ps1 picks the install spec like this:
  #
  #     $app = if ($item.Source -in $bucket_names) { "$($item.Source)/$($item.Name)" }
  #            elseif ($item.Source -eq '<auto-generated>') { "$($item.Name)@$($item.Version)" }
  #            else { $item.Source }
  #
  # Version is read in exactly one branch, the `<auto-generated>` one. That is
  # not a scoop bug: `scoop export` emits a real bucket name for a normally
  # installed app and `<auto-generated>` for one installed at a pinned version
  # (`scoop install app@1.2.3` synthesises a manifest), so import is a faithful
  # inverse of export. We emit a bucket name *and* a Version — a combination
  # export never produces — so the Version is silently dropped.
  #
  # Rather than lie to `scoop import`, the activation step below enforces pins
  # itself by reading each installed app's manifest. The Version field stays in
  # the file because it is valid scoopfile syntax and keeps the artifact a
  # complete description of intent.
  scoopfileContent = {
    buckets = lib.mapAttrsToList (name: source: {
      Name = name;
      Source = source;
    }) cfg.buckets;
    apps = lib.mapAttrsToList (
      name: pkg:
      { Name = name; Source = pkg.bucket; Info = "64bit"; }
      // lib.optionalAttrs (pkg.version != null) { Version = pkg.version; }
    ) cfg.packages;
  };

  scoopfile = pkgs.writeText "scoopfile.json" (builtins.toJSON scoopfileContent);
in
{
  options.scoop = {
    enable = lib.mkEnableOption "Scoop package management";

    buckets = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "Scoop buckets as name → source URL.";
      example = lib.literalExpression ''
        {
          main = "https://github.com/ScoopInstaller/Main";
          extras = "https://github.com/ScoopInstaller/Extras";
        }
      '';
    };

    packages = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.submodule {
          options.bucket = lib.mkOption {
            type = lib.types.str;
            description = "Which bucket this package comes from.";
          };
          options.version = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = ''
              Pin to a specific package version. When null (default), Scoop
              installs whatever the bucket currently ships and an
              already-installed package is left at whatever version it has.

              When set, activation compares it against the installed
              package's own manifest and runs
              `scoop install <bucket>/<name>@<version>` if they differ.
              Enforced by nix-win directly rather than by `scoop import`,
              which ignores the Version field for bucket-sourced entries —
              see the note above `scoopfileContent`.
            '';
          };
        }
      );
      default = { };
      description = "Scoop packages to install, keyed by package name.";
      example = lib.literalExpression ''
        {
          bat = { bucket = "main"; version = "0.26.1"; };
          autohotkey = { bucket = "extras"; };
        }
      '';
    };

    cleanup = lib.mkOption {
      type = lib.types.enum [
        "none"
        "uninstall"
      ];
      default = "none";
      description = ''
        Cleanup strategy for packages not in the config.
        "none": leave extra packages alone.
        "uninstall": remove packages not declared here.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    system.build.scoopfile = scoopfile;

    # Converge Scoop by reading state off disk and shelling out only for the
    # packages that actually differ.
    #
    # This deliberately does NOT call `scoop import`, which spawned a
    # `scoop install` per declared app and, worse, hid a full `scoop update`:
    # scoop-install.ps1 calls `is_scoop_outdated` (true once the recorded
    # LAST_UPDATE is >= 3 hours old, lib/core.ps1) and then runs
    # scoop-update.ps1, which git-fetches the scoop repo and *every* bucket.
    # On a converged machine that bought nothing and cost ~13 s every 3 hours
    # on top of ~1.6 s of no-op installs every single switch.
    #
    # Reading `apps/<name>/current/manifest.json` gives the installed version
    # authoritatively for ~0.08 s across two dozen apps and spawns no process
    # at all, so a converged run now touches Scoop zero times.
    #
    # `scoop install` does accept `-u` / `--no-update-scoop` to suppress that
    # refresh, and it is deliberately NOT passed here: we only ever invoke
    # scoop when something genuinely needs installing, which is exactly when
    # fresh bucket manifests are wanted. The fix is to stop calling scoop on
    # the converged path, not to call it with a staler view.
    system.activationScripts.scoop.text = ''
        Write-Host "nix-win: converging Scoop packages..." -ForegroundColor Cyan
        $scoopfile = Join-Path $env:NIX_WIN_STORE_PATH "scoop\scoopfile.json"
        if (-not (Get-Command scoop -ErrorAction SilentlyContinue)) {
            Write-Warning "Scoop is not installed, skipping package convergence."
        } else {
            $spec = Get-Content -LiteralPath $scoopfile -Raw | ConvertFrom-Json
            $scoopRoot = if ($env:SCOOP) { $env:SCOOP } else { Join-Path $env:USERPROFILE 'scoop' }
            $scoopFailures = @()

            # ── Buckets ───────────────────────────────────────────────────
            $bucketDir = Join-Path $scoopRoot 'buckets'
            $haveBuckets = @()
            if (Test-Path -LiteralPath $bucketDir) {
                $haveBuckets = @((Get-ChildItem -LiteralPath $bucketDir -Directory).Name)
            }
            foreach ($b in $spec.buckets) {
                if ($haveBuckets -contains $b.Name) {
                    Write-Host "  bucket $($b.Name) ok" -ForegroundColor DarkGray
                } else {
                    try {
                        scoop bucket add $b.Name $b.Source
                        if ($LASTEXITCODE -ne 0) { throw "scoop bucket add exited $LASTEXITCODE" }
                        Write-Host "  bucket $($b.Name) added" -ForegroundColor Green
                    } catch {
                        $scoopFailures += "bucket $($b.Name): $($_.Exception.Message)"
                        Write-Host "  bucket $($b.Name) FAILED: $($_.Exception.Message)" -ForegroundColor Red
                    }
                }
            }

            # ── Apps ──────────────────────────────────────────────────────
            # One manifest read per app; scoop is invoked only on a miss.
            foreach ($a in $spec.apps) {
                # Set-StrictMode makes a missing property a hard error, so
                # probe for Version rather than dereferencing it blind.
                $want = $null
                if ($a.PSObject.Properties.Name -contains 'Version') { $want = $a.Version }

                $manifest = Join-Path $scoopRoot "apps\$($a.Name)\current\manifest.json"
                $have = $null
                if (Test-Path -LiteralPath $manifest) {
                    try {
                        $have = (Get-Content -LiteralPath $manifest -Raw | ConvertFrom-Json).version
                    } catch {
                        # Unreadable manifest: treat as not installed and let
                        # scoop re-assert rather than trusting a partial read.
                        $have = $null
                    }
                }

                $spec2 = "$($a.Source)/$($a.Name)"
                if ($null -eq $have) {
                    $reason = 'not installed'
                } elseif ($null -ne $want -and $have -ne $want) {
                    $reason = "pinned $want, found $have"
                } else {
                    $shown = if ($null -ne $have) { $have } else { 'present' }
                    Write-Host "  $($a.Name) ok ($shown)" -ForegroundColor DarkGray
                    continue
                }

                if ($null -ne $want) { $spec2 = "$spec2@$want" }
                try {
                    Write-Host "  $($a.Name) installing ($reason)" -ForegroundColor Yellow
                    scoop install $spec2
                    if ($LASTEXITCODE -ne 0) { throw "scoop install exited $LASTEXITCODE" }
                    Write-Host "  $($a.Name) changed" -ForegroundColor Green
                } catch {
                    $scoopFailures += "$($a.Name): $($_.Exception.Message)"
                    Write-Host "  $($a.Name) FAILED: $($_.Exception.Message)" -ForegroundColor Red
                }
            }
        ${lib.optionalString (cfg.cleanup == "uninstall") ''
              # Remove packages not in the config. Enumerate apps\ directly
              # rather than parsing `scoop list`, which costs a ~0.9 s spawn
              # to report what the directory already states.
              $declared = @(${
                lib.concatMapStringsSep ", " (name: "'${name}'") (builtins.attrNames cfg.packages)
              })
              $appDir = Join-Path $scoopRoot 'apps'
              if (Test-Path -LiteralPath $appDir) {
                  foreach ($d in (Get-ChildItem -LiteralPath $appDir -Directory)) {
                      if ($d.Name -eq 'scoop') { continue }
                      if ($d.Name -notin $declared) {
                          try {
                              Write-Host "  $($d.Name) uninstalling (undeclared)" -ForegroundColor Yellow
                              scoop uninstall $d.Name
                              if ($LASTEXITCODE -ne 0) { throw "scoop uninstall exited $LASTEXITCODE" }
                              Write-Host "  $($d.Name) removed" -ForegroundColor Green
                          } catch {
                              $scoopFailures += "$($d.Name): $($_.Exception.Message)"
                              Write-Host "  $($d.Name) FAILED: $($_.Exception.Message)" -ForegroundColor Red
                          }
                      }
                  }
              }
        ''}
            # Fail the step once, after every package has had its turn, so one
            # bad package cannot mask the state of the rest.
            if ($scoopFailures.Count -gt 0) {
                throw "scoop: $($scoopFailures.Count) package(s) failed:`n  " + ($scoopFailures -join "`n  ")
            }
        }
      '';
  };
}
