# WinGet package manager module for nix-win.
# Declares GUI applications to install via winget.
# Standalone from DSC for simplicity and transparency.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.win.winget;

  upgradeFlag = if cfg.upgrade then "" else " --no-upgrade";

  # Generate a PowerShell install script
  installScript = pkgs.writeText "winget-install.ps1" (
    ''
      # WinGet package installation — generated by nix-win
      $ErrorActionPreference = 'Continue'
    ''
    + lib.concatStringsSep "\n" (
      lib.mapAttrsToList (
        id: pkg:
        ''
          Write-Host "  winget: ${id}" -ForegroundColor Gray
          winget install --id "${id}" --source "${pkg.source}" --accept-source-agreements --accept-package-agreements --silent${upgradeFlag} 2>$null
        ''
      ) cfg.packages
    )
  );
in
{
  options.win.winget = {
    enable = lib.mkEnableOption "WinGet package management";

    upgrade = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Whether to upgrade already-installed packages. When false (default), winget will skip packages that are already installed.";
    };

    packages = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.submodule {
          options.source = lib.mkOption {
            type = lib.types.str;
            default = "winget";
            description = "WinGet source name.";
          };
        }
      );
      default = { };
      description = "WinGet packages to install, keyed by package ID.";
      example = lib.literalExpression ''
        {
          "Microsoft.PowerShell" = {};
          "AgileBits.1Password" = {};
        }
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    system.build.wingetScript = installScript;

    win.activationScripts.winget.text = ''
        Write-Host "nix-win: installing WinGet packages..." -ForegroundColor Cyan
        $script = Join-Path $env:NIX_WIN_STORE_PATH "winget\install.ps1"
        if (Get-Command winget -ErrorAction SilentlyContinue) {
            & $script
        } else {
            Write-Warning "WinGet is not available, skipping."
        }
      '';
  };
}
