# home.activation — the per-user activation DAG, with home-manager's exact
# option shape (lib.hm.types.dagOf over lines of PowerShell). Modules and
# consumers order entries with lib.hm.dag.entryAfter/entryBefore, exactly as
# under home-manager; the text is PowerShell rather than bash (the one
# documented deviation — activation bodies are inherently per-OS).
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.home.activation;

  sortedEntries =
    let
      sorted = lib.hm.dag.topoSort cfg;
    in
    if sorted ? result then
      sorted.result
    else
      throw "nix-win: dependency cycle in home.activation: ${builtins.toJSON sorted.cycle}";

  sections = map (entry: ''
    # ── ${entry.name} ──────────────────────────────────────────────
    ${entry.data}
  '') sortedEntries;
in
{
  options.home.activation = lib.mkOption {
    type = lib.hm.types.dagOf lib.types.lines;
    default = { };
    description = ''
      Per-user activation snippets (PowerShell), ordered as a DAG with
      `lib.hm.dag.entryAfter` / `entryBefore`. Files and links are
      deployed by the nix-win CLI *before* this script runs, so the
      built-in `writeBoundary` node is trivially satisfied — it exists
      so `entryAfter [ "writeBoundary" ]` sorts the same way it does
      under home-manager.
    '';
  };

  config = {
    # The boundary marker every file-writing-dependent entry hooks after.
    home.activation.writeBoundary = lib.hm.dag.entryAnywhere ''
      # writeBoundary: home files and links were deployed by the CLI
      # before this script started; nothing to do.
    '';

    home.build.activationScript = pkgs.writeText "home-activate.ps1" ''
      # nix-win per-user activation script
      # Generated by nix-win — do not edit manually.
      $ErrorActionPreference = 'Stop'
      Set-StrictMode -Version Latest

      # Broadcast WM_SETTINGCHANGE so running Explorer / shell sessions
      # refresh their environment after HKCU\Environment edits.
      $script:NixWinEnvType = $null
      function Invoke-NixWinSettingChange {
          if (-not $script:NixWinEnvType) {
              $sig = @'
      [DllImport("user32.dll", SetLastError=true, CharSet=CharSet.Auto)]
      public static extern IntPtr SendMessageTimeout(
          IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam,
          uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
      '@
              try {
                  # -PassThru returns an array of generated types; take the
                  # first explicitly rather than relying on single-element
                  # unrolling.
                  $script:NixWinEnvType = @(Add-Type -MemberDefinition $sig -Name 'NixWinEnv' `
                      -Namespace 'NixWin' -PassThru)[0]
              } catch {
                  # Add-Type fails if the type already exists in this session
                  # (activation dot-sourced twice) — recover it. Anything else
                  # must be LOUD: a silently skipped broadcast means running
                  # sessions never see HKCU environment changes.
                  $script:NixWinEnvType = 'NixWin.NixWinEnv' -as [type]
                  if (-not $script:NixWinEnvType) {
                      Write-Warning "nix-win: WM_SETTINGCHANGE helper failed to compile ($($_.Exception.Message)); running sessions will not see HKCU environment changes until re-login."
                  }
              }
          }
          if ($script:NixWinEnvType) {
              $HWND_BROADCAST = [IntPtr]0xffff
              $WM_SETTINGCHANGE = 0x001A
              $SMTO_ABORTIFHUNG = 0x0002
              [UIntPtr]$result = [UIntPtr]::Zero
              [void]$script:NixWinEnvType::SendMessageTimeout(
                  $HWND_BROADCAST, $WM_SETTINGCHANGE, [UIntPtr]::Zero, 'Environment',
                  $SMTO_ABORTIFHUNG, 5000, [ref]$result)
          }
      }

      ${lib.concatStringsSep "\n" sections}

      Write-Host "nix-win: home activation complete." -ForegroundColor Green
    '';
  };
}
