# home.activation — the per-user activation DAG, with home-manager's exact
# option shape (lib.hm.types.dagOf over lines of PowerShell). Modules and
# consumers order entries with lib.hm.dag.entryAfter/entryBefore, exactly as
# under home-manager; the text is PowerShell rather than bash (the one
# documented deviation — activation bodies are inherently per-OS).
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.home.activation;

  activationLib = import ../../lib/activation.nix { inherit lib; };

  sortedEntries =
    let
      sorted = lib.hm.dag.topoSort cfg;
    in
    if sorted ? result then
      sorted.result
    else
      throw "nix-win: dependency cycle in home.activation: ${builtins.toJSON sorted.cycle}";

  # Same per-phase timing brackets as the system scope, emitting into the same
  # spool with stage = "home". Plain statements, not a wrapping scriptblock:
  # entries share state and rely on `return` not being swallowed.
  sections = map (entry: ''
    # ── ${entry.name} ──────────────────────────────────────────────
    $__nixwin_t0 = [System.Diagnostics.Stopwatch]::StartNew()
    try {
    ${entry.data}
    } catch {
        $__nixwin_t0.Stop()
        Emit-NixWinTiming -Stage 'home' -Step '${entry.name}' `
            -DurationMs $__nixwin_t0.Elapsed.TotalMilliseconds -ExitCode 1
        throw
    }
    $__nixwin_t0.Stop()
    Emit-NixWinTiming -Stage 'home' -Step '${entry.name}' `
        -DurationMs $__nixwin_t0.Elapsed.TotalMilliseconds -ExitCode 0
  '') sortedEntries;
in
{
  options.home.activation = lib.mkOption {
    type = lib.hm.types.dagOf lib.types.lines;
    default = { };
    description = ''
      Per-user activation snippets (PowerShell), ordered as a DAG with
      `lib.hm.dag.entryAfter` / `entryBefore`. Files and links are
      deployed by the nix-win CLI *before* this script runs, so the
      built-in `writeBoundary` node is trivially satisfied — it exists
      so `entryAfter [ "writeBoundary" ]` sorts the same way it does
      under home-manager.
    '';
  };

  config = {
    # The boundary marker every file-writing-dependent entry hooks after.
    home.activation.writeBoundary = lib.hm.dag.entryAnywhere ''
      # writeBoundary: home files and links were deployed by the CLI
      # before this script started; nothing to do.
    '';

    home.build.activationScript = pkgs.writeText "home-activate.ps1" ''
      # nix-win per-user activation script
      # Generated by nix-win — do not edit manually.
      $ErrorActionPreference = 'Stop'
      Set-StrictMode -Version Latest

      ${activationLib.timingPrelude}

      # Did this switch actually rewrite one of the given files? The CLI
      # publishes the set of target paths its deploy pass wrote (see
      # Publish-ChangedFiles) so a step can restart a daemon only when the
      # config it reads genuinely moved, instead of on every switch.
      #
      # Returns $true when the answer is unknown — no published list, or an
      # unreadable one — so an older CLI, or a scope that never deployed,
      # keeps the previous always-act behaviour rather than silently never
      # reloading anything.
      $script:NixWinChangedFiles = $null
      function Test-NixWinFileChanged {
          param([Parameter(Mandatory)][string[]]$Path)
          if ($null -eq $script:NixWinChangedFiles) {
              if (-not $env:NIX_WIN_CHANGED_FILES -or
                  -not (Test-Path -LiteralPath $env:NIX_WIN_CHANGED_FILES)) {
                  return $true
              }
              try {
                  $raw = Get-Content -LiteralPath $env:NIX_WIN_CHANGED_FILES -Raw
                  # "nothing changed" is the common case and must not be the
                  # fragile one, so build the empty set up front and only
                  # replace it when there is genuinely something to parse.
                  #
                  # Written as statements rather than `$x = if (…) { @() } …`:
                  # an empty array in a value position enumerates to ZERO
                  # pipeline objects, so that assignment yields $null, the
                  # HashSet constructor throws on a null collection, and the
                  # catch below reports "assuming everything changed" — turning
                  # a converged switch into a full reload of everything. The
                  # same unrolling is why $parsed is null-checked instead of
                  # being trusted to be an array.
                  $entries = [string[]]@()
                  if (-not [string]::IsNullOrWhiteSpace($raw)) {
                      $parsed = @($raw | ConvertFrom-Json)
                      if ($null -ne $parsed) { $entries = [string[]]$parsed }
                  }
                  $script:NixWinChangedFiles = [System.Collections.Generic.HashSet[string]]::new(
                      $entries, [System.StringComparer]::OrdinalIgnoreCase)
              } catch {
                  Write-Warning "nix-win: could not read the changed-file list ($($_.Exception.Message)); assuming everything changed."
                  return $true
              }
          }
          foreach ($p in $Path) {
              if ($script:NixWinChangedFiles.Contains($p)) { return $true }
          }
          return $false
      }

      # Broadcast WM_SETTINGCHANGE so running Explorer / shell sessions
      # refresh their environment after HKCU\Environment edits.
      $script:NixWinEnvType = $null
      function Invoke-NixWinSettingChange {
          if (-not $script:NixWinEnvType) {
              $sig = @'
      [DllImport("user32.dll", SetLastError=true, CharSet=CharSet.Auto)]
      public static extern IntPtr SendMessageTimeout(
          IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam,
          uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
      '@
              try {
                  # -PassThru returns an array of generated types; take the
                  # first explicitly rather than relying on single-element
                  # unrolling.
                  $script:NixWinEnvType = @(Add-Type -MemberDefinition $sig -Name 'NixWinEnv' `
                      -Namespace 'NixWin' -PassThru)[0]
              } catch {
                  # Add-Type fails if the type already exists in this session
                  # (activation dot-sourced twice) — recover it. Anything else
                  # must be LOUD: a silently skipped broadcast means running
                  # sessions never see HKCU environment changes.
                  $script:NixWinEnvType = 'NixWin.NixWinEnv' -as [type]
                  if (-not $script:NixWinEnvType) {
                      Write-Warning "nix-win: WM_SETTINGCHANGE helper failed to compile ($($_.Exception.Message)); running sessions will not see HKCU environment changes until re-login."
                  }
              }
          }
          if ($script:NixWinEnvType) {
              $HWND_BROADCAST = [IntPtr]0xffff
              $WM_SETTINGCHANGE = 0x001A
              $SMTO_ABORTIFHUNG = 0x0002
              [UIntPtr]$result = [UIntPtr]::Zero
              [void]$script:NixWinEnvType::SendMessageTimeout(
                  $HWND_BROADCAST, $WM_SETTINGCHANGE, [UIntPtr]::Zero, 'Environment',
                  $SMTO_ABORTIFHUNG, 5000, [ref]$result)
          }
      }

      ${lib.concatStringsSep "\n" sections}

      Write-Host "nix-win: home activation complete." -ForegroundColor Green
    '';
  };
}
