name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: nix flake check
        run: nix flake check --impure --show-trace
